name: short_readable_id
description: A short human readable and easily memorable unique id generator.
version: 1.5.1
homepage: https://github.com/tejainece/short_readable_id
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=3.0.0 <4.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.0.0
