name: short_readable_id
description: A short human readable and easily memorable unique id generator.
version: 1.5.0
homepage: https://www.example.com
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
